name: Build Docs and Open PR
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Python Docs
      uses: jbheard/markdown-docs@v0.1
    - name: Open docs update PR
      uses: peter-evans/create-pull-request@v2

